name: Build YTGet

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up latest Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download latest yt-dlp.exe
      shell: pwsh
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -o yt-dlp.exe

    - name: Download ffmpeg & ffprobe
      shell: pwsh
      run: |
        curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -o ffmpeg.zip
        tar -xf ffmpeg.zip
        $ffmpegPath = Get-ChildItem -Recurse -Filter ffmpeg.exe | Select-Object -First 1
        $ffprobePath = Get-ChildItem -Recurse -Filter ffprobe.exe | Select-Object -First 1
        Copy-Item $ffmpegPath.FullName .
        Copy-Item $ffprobePath.FullName .

    - name: Build with PyInstaller
      shell: pwsh
      run: |
        pyinstaller --noconfirm --onedir --windowed `
          --icon "icon.ico" `
          --name "YTGet" `
          --clean --noupx `
          --version-file "version_info.txt" `
          --hidden-import "PySide6.QtCore" `
          --hidden-import "PySide6.QtGui" `
          --hidden-import "PySide6.QtWidgets" `
          --hidden-import "requests" `
          --hidden-import "mutagen" `
          --hidden-import "PIL" `
          --hidden-import "webbrowser" `
          --hidden-import "mutagen.id3" `
          --hidden-import "mutagen.flac" `
          --add-data "__init__.py;." `
          --add-data "ffmpeg.exe;." `
          --add-data "ffprobe.exe;." `
          --add-data "icon.ico;." `
          --add-data "LICENSE;." `
          --add-data "main_window.py;." `
          --add-data "README.md;." `
          --add-data "settings.py;." `
          --add-data "styles.py;." `
          --add-data "yt-dlp.exe;." `
          --add-data "dialogs;dialogs/" `
          --add-data "utils;utils/" `
          --add-data "widgets;widgets/" `
          --add-data "workers;workers/" `
          "main.py"

    - name: Zip build
      shell: pwsh
      run: Compress-Archive -Path dist/YTGet -DestinationPath YTGet.zip -CompressionLevel Optimal

    - name: Upload to existing GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: YTGet.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
