name: Build & Cross Release YTGet

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to release'
        required: true
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  APP_NAME: YTGet
  ENTRY_POINT: ytget_gui.main:main

jobs:
  windows:
    name: 🪟 Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps & PyInstaller
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Download yt-dlp.exe & ffmpeg builds
        shell: pwsh
        run: |
          curl -sL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -o yt-dlp.exe
          curl -sL https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -o ffmpeg.zip
          tar -xf ffmpeg.zip
          Copy-Item (Get-ChildItem -Recurse -Filter ffmpeg.exe | Select-Object -First 1).FullName .
          Copy-Item (Get-ChildItem -Recurse -Filter ffprobe.exe | Select-Object -First 1).FullName .

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onedir --windowed `
            --name "$env:APP_NAME" `
            --icon "ytget_gui/icon.ico" `
            --clean --noupx `
            --version-file "version_info.txt" `
            --add-data "yt-dlp.exe;." `
            --add-data "ffmpeg.exe;." `
            --add-data "ffprobe.exe;." `
            "ytget_gui/main.py"

      - name: Zip Windows build
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/$env:APP_NAME/*" `
                           -DestinationPath "${env:APP_NAME}-windows.zip"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: YTGet-windows.zip

  linux:
    name: 🐧 Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (incl. linuxdeployqt)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-pip python3-setuptools \
            qt5-default qttools5-dev-tools libqt5svg5-dev fuse libfuse2 ruby ruby-dev \
            rpm
          # Download the official AppImage of linuxdeployqt
          wget -qO linuxdeployqt.AppImage \
            https://github.com/linuxdeploy/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
          chmod +x linuxdeployqt.AppImage
          sudo mv linuxdeployqt.AppImage /usr/local/bin/linuxdeployqt

      - name: Install Python deps & PyInstaller
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt pyinstaller fpm

      - name: Download yt-dlp & ffmpeg
        run: |
          curl -sL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
          chmod +x yt-dlp
          curl -sL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
            | tar -xJ --strip-components=1 ffmpeg*/{ffmpeg,ffprobe}

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed \
            --name "$APP_NAME" \
            --icon "ytget_gui/icon.png" \
            --clean --noupx \
            --version-file "version_info.txt" \
            --add-data "yt-dlp:." \
            --add-data "ffmpeg:." \
            --add-data "ffprobe:." \
            ytget_gui/main.py

      - name: Create AppImage
        run: |
          linuxdeployqt \
            "dist/$APP_NAME/$APP_NAME.desktop" \
            -appimage \
            -bundle-non-qt-libs

      - name: Build DEB & RPM with fpm
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          fpm -s dir -t deb \
            --name "$APP_NAME" \
            --version "$VERSION" \
            --license MIT \
            --url "https://github.com/ErfanNamira/ytget-gui" \
            --depends python3,python3-pyside6,python3-requests \
            --prefix /opt/$APP_NAME \
            dist/$APP_NAME/=/opt/$APP_NAME \
            yt-dlp=/opt/$APP_NAME \
            ffmpeg=/opt/$APP_NAME \
            ffprobe=/opt/$APP_NAME

          fpm -s dir -t rpm \
            --name "$APP_NAME" \
            --version "$VERSION" \
            --license MIT \
            --url "https://github.com/ErfanNamira/ytget-gui" \
            --depends python3-pyside6,python3-requests \
            --prefix /opt/$APP_NAME \
            dist/$APP_NAME/=/opt/$APP_NAME \
            yt-dlp=/opt/$APP_NAME \
            ffmpeg=/opt/$APP_NAME \
            ffprobe=/opt/$APP_NAME

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-installers
          path: |
            *.AppImage
            *.deb
            *.rpm

  macos:
    name: 🍎 macOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps & PyInstaller
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt pyinstaller

      - name: Download yt-dlp & link ffmpeg
        run: |
          curl -sL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
          chmod +x yt-dlp
          brew install ffmpeg
          ln -sf "$(which ffmpeg)" ffmpeg
          ln -sf "$(which ffprobe)" ffprobe

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed \
            --name "$APP_NAME" \
            --icon "ytget_gui/icon.icns" \
            --clean --noupx \
            --version-file "version_info.txt" \
            --hidden-import PySide6.QtCore \
            --hidden-import PySide6.QtGui \
            --hidden-import PySide6.QtWidgets \
            --add-data "yt-dlp:." \
            --add-data "ffmpeg:." \
            --add-data "ffprobe:." \
            ytget_gui/main.py

      - name: Create DMG
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          hdiutil create \
            -format UDZO \
            -srcfolder "dist/$APP_NAME" \
            -volname "$APP_NAME" \
            "${APP_NAME}-${VERSION}.dmg"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-installers
          path: |
            dist/$APP_NAME
            *.dmg

  release:
    name: 🚀 Publish Release
    needs: [windows, linux, macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure tag exists
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --tags
          TAG="${{ github.event.inputs.tag }}"
          git rev-parse -q --verify "refs/tags/$TAG" || (
            git tag "$TAG" && git push origin "$TAG"
          )

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build_output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: "YTGet ${{ github.event.inputs.tag || github.ref_name }}"
          body_path: RELEASE_NOTES.md
          files: |
            build_output/*.zip
            build_output/*.AppImage
            build_output/*.deb
            build_output/*.rpm
            build_output/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
