name: Build macOS x86_64 Only

on:
  workflow_dispatch:

jobs:
  build-macos-x86_64:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o yt-dlp
        chmod +x yt-dlp

    - name: Download ffmpeg & ffprobe
      run: |
        curl -L https://evermeet.cx/ffmpeg/ffmpeg-8.0.zip -o ffmpeg.zip
        unzip ffmpeg.zip
        chmod +x ffmpeg
        curl -L https://evermeet.cx/ffmpeg/ffprobe-8.0.zip -o ffprobe.zip
        unzip ffprobe.zip
        chmod +x ffprobe

    - name: Build YTGet macOS x86_64
      run: |
        ICON="ytget_gui/icon.icns"
        APP_NAME="YTGet"
        pyinstaller --noconfirm --onedir --windowed \
          --name "$APP_NAME" \
          --icon "$ICON" \
          --clean --noupx \
          --version-file "version_info.txt" \
          --osx-bundle-identifier "com.erfannamira.ytget" \
          --hidden-import "PySide6.QtCore" \
          --hidden-import "PySide6.QtGui" \
          --hidden-import "PySide6.QtWidgets" \
          --hidden-import "requests" \
          --hidden-import "mutagen" \
          --hidden-import "PIL" \
          --hidden-import "webbrowser" \
          --hidden-import "mutagen.id3" \
          --hidden-import "mutagen.flac" \
          --add-data "ytget_gui:ytget_gui" \
          --add-data "ytget_gui/icon.icns:." \
          --add-data "yt-dlp:." \
          --add-data "ffmpeg:." \
          --add-data "ffprobe:." \
          ytget_gui/main.py
        cp Info.plist "dist/$APP_NAME.app/Contents/Info.plist"

    - name: Package
      run: |
        cd dist
        tar -czf YTGet-macOS-x86_64.tar.gz YTGet.app
        shasum -a 256 YTGet-macOS-x86_64.tar.gz > YTGet-macOS-x86_64.sha256
        cd ..

    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-x86_64
        path: dist/YTGet-macOS-x86_64.*
